base_url = "https://gtfs.zone"

theme = "daisy"

title = "gtfs.zone"
description = "A public option for transit software"

compile_sass = false
minify_html = true
build_search_index = true

default_language = "en"

generate_feeds = false

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[search]
index_format = "elasticlunr_json"

[extra]
enable_theme_switching = true
daisyui_theme_light = "light"
daisyui_theme_dark = "dark"

[extra.footer]
links = [
    { url = "realtime-setup", i18n_key = "realtime_setup" },
    { url = "sitemap.xml", i18n_key = "sitemap", no_translation = true },
]

notice = '<a href="https://gtfs.zone">gtfs.zone</a>'

[extra.navbar]
links = [
    { url = "realtime-setup", i18n_key = "realtime_setup" },
]

[extra.social]
codeberg = "https://git.kcfam.us/gtfs.zone"
github = ""
gitlab = ""
stackoverflow = ""
mastodon = ""
linkedin = ""
instagram = ""
youtube = ""
signal = ""
telegram = ""
email = ""
phone = ""

[extra.favicon]
svg = "favicon.svg"
